env: "local"
storage_path: "./storage/shortener.db"
http_server:
  address: "localhost:8082"
  timeout: 4s # Время на чтение запроса и отправку ответа
  idle_timeout: 30s # время жизни осединения с клиентом
  user: "my_user"
  password: "my_pass"
clients:
  sso:
    address: "localhost:44044"
    timeout: 4s
    retries_count: 1
app_secret: "test-secret"