env: "prod"
storage_path: "./storage.db"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "novich57"
clients:
  sso:
    address: "103.74.92.23:44044"
    timeout: 4s
    retries_count: 3
app_secret: "test-secret"